# ruff: noqa: E501
"""Bot-side i18n. Nothing user-facing is hardcoded at a call site — always go through ``t()``.

Languages: ru (primary, default), uz, en. A missing key in uz/en falls back to ru rather
than showing a raw key to a candidate.
"""

from typing import Any

DEFAULT_LANG = "ru"
SUPPORTED = ("ru", "uz", "en")

TEXTS: dict[str, dict[str, str]] = {
    "ru": {
        "welcome": "👋 Здравствуйте! Здесь вы можете посмотреть наши вакансии и откликнуться.",
        "menu_vacancies": "📋 Вакансии",
        "menu_about": "🏢 О компании",
        "menu_my_apps": "📨 Мои заявки",
        "menu_hint": "Выберите раздел:",
        "err_datetime_format": "Неверный формат. Введите как {format}. Например: {example}",
        "datetime_hint": "Формат: {format} (например: {example})",
        "apply_prompt": "Готовы откликнуться?",
        "menu_branches": "📍 Филиалы",
        "menu_news": "📰 Новости",
        "menu_contacts": "☎️ Контакты / Адрес",
        "choose_section": "Выберите раздел:",
        "hot_vacancies": "🔥 Актуальные вакансии",
        "by_branch_vacancies": "🌐 Вакансии по филиалам",
        "vacancies_menu": "🧑🏻‍🍳 Меню вакансий:",
        "hot_vacancies_title": "🔥 Сейчас открыты:",
        "no_hot_vacancies": "Сейчас нет актуальных вакансий.",
        "branches_list": "📍 Список филиалов:",
        "no_branches": "Список филиалов пока пуст.",
        "no_news": "Новостей пока нет.",
        "news_title": "📰 Новости:",
        "news_more": "➡️ Ещё новости",
        "contacts_default": "Контакты пока не заполнены.",
        "read_more": "Подробнее",
        "nothing_selected": "Ничего не выбрано",
        "menu_back": "🏠 Главное меню",
        "cancel_button": "✖️ Отменить",
        "menu_language": "🌐 Язык",
        "choose_language": "Выберите язык / Tilni tanlang / Choose a language:",
        "language_set": "Язык изменён на «Русский».",
        "about_default": "Информация о компании пока не заполнена.",
        "choose_branch": "Выберите филиал:",
        "general_vacancies": "🌐 Общие вакансии",
        "back_to_branches": "⬅️ К филиалам",
        "back": "⬅️ Назад",
        "no_vacancies": "Сейчас нет открытых вакансий. Загляните позже 🙌",
        "no_vacancies_branch": "В этом филиале сейчас нет открытых вакансий.",
        "choose_vacancy": "Выберите вакансию:",
        "apply": "✅ Откликнуться",
        "salary_from_to": "от {frm} до {to} {cur}",
        "salary_from": "от {frm} {cur}",
        "salary_to": "до {to} {cur}",
        "field_branch": "Филиал",
        "field_address": "Адрес",
        "field_city": "Город",
        "field_salary": "Зарплата",
        "field_employment": "Занятость",
        "already_applied": "Вы уже откликались на эту вакансию. Текущий статус: <b>{status}</b>",
        "form_start": "Отлично! Ответьте на несколько вопросов.\nВ любой момент можно отменить: /cancel",
        "skip": "⏭ Пропустить",
        "done": "✅ Готово",
        "share_contact": "📱 Поделиться контактом",
        "err_too_long": "Слишком длинный ответ. Максимум {max} символов.",
        "err_not_number": "Введите число.",
        "err_min": "Значение должно быть не меньше {min}.",
        "err_max": "Значение должно быть не больше {max}.",
        "err_phone": "Не похоже на номер телефона. Пример: +998901234567",
        "err_need_choice": "Выберите хотя бы один вариант.",
        "err_need_file": "Прикрепите файл или фото.",
        "err_file_too_big": "Файл слишком большой. Максимум {max} МБ.",
        "err_expect_text": "Пожалуйста, отправьте ответ текстом.",
        "err_use_buttons": "Пожалуйста, воспользуйтесь кнопками выше.",
        "summary_title": "Проверьте ваши ответы:",
        "submit": "✅ Отправить",
        "restart_form": "✏️ Заполнить заново",
        "after_apply_default": "Спасибо! Ваша заявка отправлена. Мы свяжемся с вами 🙌",
        "cancelled": "Заполнение анкеты отменено.",
        "no_applications": "У вас пока нет заявок.",
        "my_apps_title": "Ваши заявки:",
        "notify_status": "Статус вашей заявки на «{vacancy}» изменён: <b>{status}</b>",
        "answer_skipped": "— пропущено —",
        "file_received": "Файл получен ✅",
        "err_profile_photo_image": "Пожалуйста, отправьте изображение: JPEG, PNG, WebP или GIF.",
        "session_expired": "Сессия истекла. Начните заново: /start",
        "vacancy_gone": "Эта вакансия больше не доступна.",
        "applications_unavailable": "Приём заявок временно недоступен. Пожалуйста, попробуйте позже.",
        "generic_error": "Что-то пошло не так. Попробуйте ещё раз: /start",
        "bot_inactive": "Бот временно недоступен.",
        "page_prev": "⬅️",
        "page_next": "➡️",
    },
    "uz": {
        "welcome": "👋 Assalomu alaykum! Bu yerda vakansiyalarimizni ko‘rib, ariza qoldirishingiz mumkin.",
        "menu_vacancies": "📋 Vakansiyalar",
        "menu_about": "🏢 Kompaniya haqida",
        "menu_my_apps": "📨 Mening arizalarim",
        "menu_hint": "Bo‘limni tanlang:",
        "err_datetime_format": "Format noto‘g‘ri. {format} shaklida kiriting. Masalan: {example}",
        "datetime_hint": "Format: {format} (masalan: {example})",
        "apply_prompt": "Ariza qoldirasizmi?",
        "menu_branches": "📍 Filiallar",
        "menu_news": "📰 Yangiliklar",
        "menu_contacts": "☎️ Kontaktlar / Manzil",
        "choose_section": "Bo‘limni tanlang:",
        "hot_vacancies": "🔥 Dolzarb ish o‘rinlari",
        "by_branch_vacancies": "🌐 Filiallar bo‘yicha",
        "vacancies_menu": "🧑🏻‍🍳 Bo‘sh ish o‘rinlari menyusi:",
        "hot_vacancies_title": "🔥 Hozirda ochiq:",
        "no_hot_vacancies": "Hozircha dolzarb ish o‘rinlari yo‘q.",
        "branches_list": "📍 Filiallar ro‘yxati:",
        "no_branches": "Filiallar ro‘yxati hozircha bo‘sh.",
        "no_news": "Hozircha yangiliklar yo‘q.",
        "news_title": "📰 Yangiliklar:",
        "news_more": "➡️ Yana yangiliklar",
        "contacts_default": "Kontaktlar hali kiritilmagan.",
        "read_more": "Batafsil",
        "nothing_selected": "Hech narsa tanlanmagan",
        "page_prev": "⬅️",
        "page_next": "➡️",
        "menu_back": "🏠 Asosiy menyu",
        "cancel_button": "✖️ Bekor qilish",
        "menu_language": "🌐 Til",
        "choose_language": "Tilni tanlang / Выберите язык / Choose a language:",
        "language_set": "Til «O‘zbekcha» ga o‘zgartirildi.",
        "about_default": "Kompaniya haqida ma’lumot hali kiritilmagan.",
        "choose_branch": "Filialni tanlang:",
        "general_vacancies": "🌐 Umumiy vakansiyalar",
        "back_to_branches": "⬅️ Filiallarga",
        "back": "⬅️ Orqaga",
        "no_vacancies": "Hozircha ochiq vakansiyalar yo‘q. Keyinroq kiring 🙌",
        "no_vacancies_branch": "Bu filialda hozircha ochiq vakansiyalar yo‘q.",
        "choose_vacancy": "Vakansiyani tanlang:",
        "apply": "✅ Ariza qoldirish",
        "salary_from_to": "{frm} dan {to} gacha {cur}",
        "salary_from": "{frm} dan {cur}",
        "salary_to": "{to} gacha {cur}",
        "field_branch": "Filial",
        "field_address": "Manzil",
        "field_city": "Shahar",
        "field_salary": "Maosh",
        "field_employment": "Bandlik",
        "already_applied": "Siz bu vakansiyaga allaqachon ariza qoldirgansiz. Holati: <b>{status}</b>",
        "form_start": "Ajoyib! Bir nechta savolga javob bering.\nBekor qilish: /cancel",
        "skip": "⏭ O‘tkazib yuborish",
        "done": "✅ Tayyor",
        "share_contact": "📱 Kontakt yuborish",
        "err_too_long": "Javob juda uzun. Maksimum {max} belgi.",
        "err_not_number": "Raqam kiriting.",
        "err_min": "Qiymat {min} dan kam bo‘lmasligi kerak.",
        "err_max": "Qiymat {max} dan oshmasligi kerak.",
        "err_phone": "Telefon raqamiga o‘xshamaydi. Masalan: +998901234567",
        "err_need_choice": "Kamida bitta variantni tanlang.",
        "err_need_file": "Fayl yoki rasm biriktiring.",
        "err_file_too_big": "Fayl juda katta. Maksimum {max} MB.",
        "err_expect_text": "Iltimos, javobni matn ko‘rinishida yuboring.",
        "err_use_buttons": "Iltimos, yuqoridagi tugmalardan foydalaning.",
        "summary_title": "Javoblaringizni tekshiring:",
        "submit": "✅ Yuborish",
        "restart_form": "✏️ Qaytadan to‘ldirish",
        "after_apply_default": "Rahmat! Arizangiz yuborildi. Tez orada bog‘lanamiz 🙌",
        "cancelled": "Anketa to‘ldirish bekor qilindi.",
        "no_applications": "Sizda hali arizalar yo‘q.",
        "my_apps_title": "Sizning arizalaringiz:",
        "notify_status": "«{vacancy}» bo‘yicha arizangiz holati o‘zgardi: <b>{status}</b>",
        "answer_skipped": "— o‘tkazib yuborilgan —",
        "file_received": "Fayl qabul qilindi ✅",
        "err_profile_photo_image": "Iltimos, JPEG, PNG, WebP yoki GIF rasm yuboring.",
        "session_expired": "Sessiya tugadi. Qaytadan boshlang: /start",
        "vacancy_gone": "Bu vakansiya endi mavjud emas.",
        "applications_unavailable": "Arizalarni qabul qilish vaqtincha imkonsiz. Keyinroq urinib ko‘ring.",
        "generic_error": "Nimadir xato ketdi. Qaytadan urinib ko‘ring: /start",
        "bot_inactive": "Bot vaqtincha ishlamayapti.",
    },
    "en": {
        "welcome": "👋 Hi! Browse our openings and apply right here.",
        "menu_vacancies": "📋 Openings",
        "menu_about": "🏢 About us",
        "menu_my_apps": "📨 My applications",
        "menu_hint": "Pick a section:",
        "err_datetime_format": "Wrong format. Enter it as {format}. Example: {example}",
        "datetime_hint": "Format: {format} (e.g. {example})",
        "apply_prompt": "Ready to apply?",
        "menu_branches": "📍 Locations",
        "menu_news": "📰 News",
        "menu_contacts": "☎️ Contacts / Address",
        "choose_section": "Pick a section:",
        "hot_vacancies": "🔥 Current openings",
        "by_branch_vacancies": "🌐 Browse by location",
        "vacancies_menu": "🧑🏻‍🍳 Openings:",
        "hot_vacancies_title": "🔥 Open right now:",
        "no_hot_vacancies": "No featured openings right now.",
        "branches_list": "📍 Our locations:",
        "no_branches": "No locations yet.",
        "no_news": "No news yet.",
        "news_title": "📰 News:",
        "news_more": "➡️ More news",
        "contacts_default": "No contact details yet.",
        "read_more": "Read more",
        "nothing_selected": "Nothing selected",
        "page_prev": "⬅️",
        "page_next": "➡️",
        "menu_back": "🏠 Main menu",
        "cancel_button": "✖️ Cancel",
        "menu_language": "🌐 Language",
        "choose_language": "Choose a language / Выберите язык / Tilni tanlang:",
        "language_set": "Language switched to English.",
        "about_default": "No company information yet.",
        "choose_branch": "Choose a location:",
        "general_vacancies": "🌐 General openings",
        "back_to_branches": "⬅️ Back to locations",
        "back": "⬅️ Back",
        "no_vacancies": "No open positions right now. Check back soon 🙌",
        "no_vacancies_branch": "No open positions at this location right now.",
        "choose_vacancy": "Choose a position:",
        "apply": "✅ Apply",
        "salary_from_to": "from {frm} to {to} {cur}",
        "salary_from": "from {frm} {cur}",
        "salary_to": "up to {to} {cur}",
        "field_branch": "Location",
        "field_address": "Address",
        "field_city": "City",
        "field_salary": "Salary",
        "field_employment": "Employment",
        "already_applied": "You have already applied for this position. Status: <b>{status}</b>",
        "form_start": "Great! Just a few questions.\nYou can stop any time with /cancel",
        "skip": "⏭ Skip",
        "done": "✅ Done",
        "share_contact": "📱 Share contact",
        "err_too_long": "That answer is too long. Maximum {max} characters.",
        "err_not_number": "Please enter a number.",
        "err_min": "Value must be at least {min}.",
        "err_max": "Value must be at most {max}.",
        "err_phone": "That doesn't look like a phone number. Example: +998901234567",
        "err_need_choice": "Pick at least one option.",
        "err_need_file": "Please attach a file or a photo.",
        "err_file_too_big": "File is too large. Maximum {max} MB.",
        "err_expect_text": "Please send your answer as text.",
        "err_use_buttons": "Please use the buttons above.",
        "summary_title": "Please review your answers:",
        "submit": "✅ Submit",
        "restart_form": "✏️ Start over",
        "after_apply_default": "Thank you! Your application has been submitted 🙌",
        "cancelled": "Application cancelled.",
        "no_applications": "You have no applications yet.",
        "my_apps_title": "Your applications:",
        "notify_status": "Your application for “{vacancy}” changed status: <b>{status}</b>",
        "answer_skipped": "— skipped —",
        "file_received": "File received ✅",
        "err_profile_photo_image": "Please upload a JPEG, PNG, WebP, or GIF image.",
        "session_expired": "Session expired. Start again: /start",
        "vacancy_gone": "This position is no longer available.",
        "applications_unavailable": "Applications are temporarily unavailable. Please try again later.",
        "generic_error": "Something went wrong. Please try again: /start",
        "bot_inactive": "The bot is temporarily unavailable.",
    },
}


def t(lang: str | None, key: str, **kwargs: Any) -> str:
    lang = lang if lang in SUPPORTED else DEFAULT_LANG
    template = TEXTS[lang].get(key) or TEXTS[DEFAULT_LANG].get(key, key)
    if kwargs:
        try:
            return template.format(**kwargs)
        except (KeyError, IndexError):
            return template
    return template
