"""news, hot vacancies, branch geo, contacts

Revision ID: 3922d40ec968
Revises: 5422a621bfa8
Create Date: 2026-08-03 22:48:38.709871
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3922d40ec968'
down_revision: Union[str, None] = '5422a621bfa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True,
              server_default=sa.text("'{}'::jsonb")),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_company', 'news', ['company_id', 'sort_order'], unique=False)
    op.add_column('bots', sa.Column('contacts_text', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('photo_url', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('branches', sa.Column('longitude', sa.Float(), nullable=True))
    # server_default is required: existing vacancies have no value for a NOT NULL column,
    # so adding it without one fails outright on any non-empty table.
    op.add_column(
        'vacancies',
        sa.Column('is_hot', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('vacancies', sa.Column('photo_url', sa.Text(), nullable=True))
    op.create_index('ix_vacancies_company_hot', 'vacancies', ['company_id', 'is_hot', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_company_hot', table_name='vacancies')
    op.drop_column('vacancies', 'photo_url')
    op.drop_column('vacancies', 'is_hot')
    op.drop_column('branches', 'longitude')
    op.drop_column('branches', 'latitude')
    op.drop_column('branches', 'photo_url')
    op.drop_column('bots', 'contacts_text')
    op.drop_index('ix_news_company', table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
